apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: applications
  annotations:
    github.com/project-slug: sriharsha-rv/applications
spec:
  type: other
  lifecycle: unknown
  owner: guests
