---
apiVersion: v1
kind: Namespace
metadata:
  name: app3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: app3
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - image: hello-world:nanoserver-ltsc2022
        name: app3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app3
  namespace: app3
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app3
